services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: traxs-fe-container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always